version: "2"
services:
  database:
    image: 'bitnami/mongodb:3.6'
    labels:
       kompose.service.type: nodeport
    ports:
       - "27017:27017"
    volumes:
       - 'mongodb_data:/bitnami'
    expose:
       - "27017"
  application:
    image: "node:10.15.2-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=master
    volumes:
      - ../:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run master"

volumes:
  mongodb_data:
    driver: local


