version: "2"
services:
  application:
    image: "node:10.15.2-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=master
    volumes:
      - ../:/home/node/app
    expose:
      - "8081"
    command: "npm run master"
